version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=root
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      - ALLOW_OVERRIDE=true
    links:
      - db:db
volumes:
  db: {}
  wordpress: {}
