version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  web:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - web:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://wordpress.local');
        define('WP_SITEURL', 'http://wordpress.local');
        define('FS_METHOD', 'direct');
volumes:
  db: {}
  web: {}
